import { describe, expect, it } from 'vitest'
import { critterRamp, renderScene, sceneFor, sceneLine, type SceneId } from './companionScenes'
import { CRITTER, CRITTER_H, CRITTER_W } from './critterSprites'

const SCENES: SceneId[] = ['garden', 'volcano', 'building', 'digging', 'waiting', 'approval', 'mail', 'party', 'storm', 'night']
const W = 64
const H = 96

describe('sceneFor', () => {
  it('follows the agent state first', () => {
    expect(sceneFor('sleeping')).toBe('night')
    expect(sceneFor('error')).toBe('storm')
    expect(sceneFor('done')).toBe('party')
    expect(sceneFor('attention')).toBe('mail')
    expect(sceneFor('waiting')).toBe('waiting')
    expect(sceneFor('waiting', { kind: 'approval', title: 'Waiting for approval' })).toBe('approval')
  })

  it('acts out the latest event while working', () => {
    expect(sceneFor('working', { kind: 'tool', title: 'Running tests', detail: 'npm test' })).toBe('volcano')
    expect(sceneFor('working', { kind: 'tool', title: 'Editing files' })).toBe('building')
    expect(sceneFor('working', { kind: 'activity', title: 'Inspecting project' })).toBe('digging')
    expect(sceneFor('working')).toBe('garden')
  })
})

describe('renderScene', () => {
  it('fills the whole requested pixel grid', () => {
    for (const scene of SCENES) {
      for (const [w, h] of [[W, H], [40, 60], [80, 200]]) {
        const frame = renderScene(scene, 12, w, h)
        expect(frame.width).toBe(w)
        expect(frame.height).toBe(h)
        expect(frame.pixels).toHaveLength(w * h)
        expect(frame.pixels.every((pixel) => pixel !== null), scene).toBe(true)
      }
    }
  })

  it('draws the shaded critter (ramp tones + outline) in every scene', () => {
    for (const scene of SCENES) {
      const pixels = renderScene(scene, 12, W, H).pixels
      for (const tone of ['r1', 'r2', 'r3', 'line']) expect(pixels, `${scene}/${tone}`).toContain(tone)
    }
  })

  it('gives the critter eyes in every scene', () => {
    for (const scene of SCENES) expect(renderScene(scene, 12, W, H).pixels, scene).toContain('ink')
  })

  it('animates every scene', () => {
    for (const scene of SCENES) {
      const frames = new Set(Array.from({ length: 30 }, (_, tick) => renderScene(scene, tick, W, H).pixels.join(',')))
      expect(frames.size, scene).toBeGreaterThan(1)
    }
  })

  it('is deterministic for the same tick', () => {
    for (const scene of SCENES) expect(renderScene(scene, 33, W, H)).toEqual(renderScene(scene, 33, W, H))
  })

  it('puts the scene props on stage', () => {
    expect(renderScene('volcano', 12, W, H).pixels).toContain('lava')
    expect(renderScene('building', 40, W, H).pixels).toContain('brick')
    expect(renderScene('digging', 12, W, H).pixels).toContain('pit')
    expect(renderScene('storm', 0, W, H).pixels).toContain('rain')
    expect(renderScene('night', 12, W, H).pixels).toContain('moon')
    expect(renderScene('party', 12, W, H).pixels.filter((p) => ['red', 'gold', 'green', 'blue', 'pink', 'cyan'].includes(p as string)).length).toBeGreaterThan(5)
  })

  it('always has a speech bubble, plus the command on the volcano', () => {
    for (const scene of SCENES) expect(renderScene(scene, 0, W, H).texts.some((t) => t.kind === 'bubble' && t.text.length > 0), scene).toBe(true)
    const volcano = renderScene('volcano', 0, W, H, { title: 'Running tests', detail: 'npm test' })
    expect(volcano.texts.find((t) => t.kind === 'label')?.text).toBe('npm test')
  })

  it('shows z\'s while asleep', () => {
    expect(renderScene('night', 9, W, H).texts.some((t) => t.kind === 'float' && /z/i.test(t.text))).toBe(true)
  })

  it('tolerates tiny sizes and odd ticks', () => {
    expect(() => renderScene('garden', -5, 1, 1)).not.toThrow()
    expect(renderScene('garden', 2.6, W, H)).toEqual(renderScene('garden', 2, W, H))
  })
})

describe('sceneLine', () => {
  it('rotates through lines and fills in the command', () => {
    expect(sceneLine('volcano', 0)).not.toBe(sceneLine('volcano', 70))
    expect(sceneLine('volcano', 70, { detail: 'pnpm vitest' })).toContain('pnpm vitest')
  })
})

describe('critter sprites (generated by art/critter/build.py)', () => {
  it('every pose has the declared size and only known tokens', () => {
    for (const [name, sprite] of Object.entries(CRITTER)) {
      expect(sprite.rows, name).toHaveLength(CRITTER_H)
      for (const row of sprite.rows) expect(row, name).toMatch(new RegExp(`^[.o0-4]{${CRITTER_W}}$`))
      // The eyes sit on the body, not in the air.
      const [ex, ey] = sprite.eyes
      expect(sprite.rows[ey][ex], name).not.toBe('.')
      expect(sprite.rows[ey][ex + sprite.eyeGap], name).not.toBe('.')
    }
  })

  it('has the poses the scenes use', () => {
    for (const pose of ['idle0', 'idle1', 'walk0', 'walk1', 'walk2', 'walk3', 'crouch', 'air', 'land', 'cheer', 'sit']) expect(CRITTER).toHaveProperty(pose)
  })
})

describe('critterRamp', () => {
  it('matches pixel-art-studio ramp() exactly, so the preview and the app agree', () => {
    expect(critterRamp([0xd9, 0x77, 0x57]).ramp).toEqual(['#822221', '#a04234', '#d97757', '#da9a75', '#f7cda6'])
    expect(critterRamp([0x3b, 0x82, 0xf6]).ramp).toEqual(['#071c94', '#1940ae', '#3b82f6', '#5da0e3', '#93d4fd'])
  })

  it('outlines in a near-black of the same family', () => {
    const { line } = critterRamp([0xd9, 0x77, 0x57])
    const value = Math.max(...[1, 3, 5].map((i) => parseInt(line.slice(i, i + 2), 16)))
    expect(value).toBeLessThan(70)
  })
})

describe('listening', () => {
  it('says so in the bubble while you type, except asleep or in a storm', () => {
    const bubble = (scene: SceneId, listening: boolean): string | undefined => renderScene(scene, 0, W, H, undefined, listening).texts.find((t) => t.kind === 'bubble')?.text
    expect(bubble('garden', true)).toBe('Listening...')
    expect(bubble('garden', false)).not.toBe('Listening...')
    expect(bubble('night', true)).not.toBe('Listening...')
  })
})
